language: cpp
sudo: required
dist: trusty
compiler: gcc
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: ./configure && make && make arduino && make test
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y arduino
