language: cpp
sudo: required
dist: trusty
compiler: gcc
before_script:
  - ./configure
  - mkdir build
  - cd build
  - cmake -Dtest=ON -DMAKE_SIM=ON ..
script: make && make due && ./runConsoleTests
before_install:
  - sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
  - wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
  - sudo apt-get -qq update
  - sudo apt-get install -y arduino gazebo7 libgazebo7-dev
